apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kpekepsalt/middle-grade-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: CAMUNDA_TASK_LIST_LOGIN
            valueFrom:
              secretKeyRef:
                name: tasklist-auth
                key: login
          - name: CAMUNDA_TASK_LIST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tasklist-auth
                key: password
          - name: DATASOURCE_USER
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: user
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-auth
                key: password
          - name: DATASOURCE_URL
            value: "jdbc:postgresql://host.docker.internal:5432/nlmkend"
          - name: TASK_LIST_URL
            value: "http://host.docker.internal:8082"
          - name: ZEEBE_URL
            value: "host.docker.internal:26500"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
