server:
  port: 8097
spring:
  application:
    name: statistic-service
  main:
    lazy-initialization: false
  kafka:
    bootstrap-servers: localhost:9095
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    password:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  flyway:
    enabled: true
    url: jdbc:clickhouse://localhost:8123/default
    user: default
    password:
    locations: classpath:db/migration
    placeholders:
      kafka-bootstrap-servers: 'localhost:9095'
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-handlers-package: ru.danilarassokhin.statistic.typehandler
  configuration:
    map-underscore-to-camel-case: true
app:
  events:
    topic: game.event
